- name: Install and Configure Dockerized lamp stack with a simple test application
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Install packages
      apt: 
        update_cache: yes 
        name: "{{ packages }}" 
        state: present
      vars:
        packages:
        - git
        - python-pip
        - curl
        - haproxy
    
   #- name: Configure haproxy
   #   template:
   #     src: "templates/haproxy.cfg.j2"
   #     dest: "/etc/haproxy/haproxy.cfg"
   #   become: yes

   #- name: Restart haproxy service
   #   service:
   #     name: haproxy
   #     state: restarted
   #   become: yes  
 
